### ISSUE TITLE
VPN App Across User Profiles

### ISSUE THREAD

**Issue by rhclayto** [Peter-Easton/GrapheneOS-Knowledge#2]
First, I don't know the right non-Reddit place to ask GrapheneOS questions. (I don't have a Reddit account.) So apologies for posting one here, but this was the only issue tracker I found that seemed to be along the lines of FAQs/general user information.

I use an application that runs as an app-defined Android VPN (InviZible Pro). Here is the link to my question over on that project: https://github.com/Gedsh/InviZible/issues/82 It routes network traffic through Tor (like Orbot), & DNS requests through DNSCrypt servers. I would like the VPN functionality (always on, block all traffic when not on) to apply to all user profiles. It works flawlessly in the Owner profile. But it does not have any effect on traffic in user profiles. Installing the application in a user profile doesn't work either, because it doesn't show up as a candidate for VPN in the Android VPN settings.

According to the developer of that app, 'So it looks like GrapheneOS doesn't support managing apps in user profiles from the main profile in VPN mode.' Is this the case?

More generally, is it possible to have an app-defined VPN that applies to all user profiles with GrapheneOS? If so, any pointers how to accomplish it would be appreciated. If not, I think it might be something worth making possible in GrapheneOS.

**Comment by Peter-Easton** [comment]
Ahoy rhclayto!

This FAQ is somewhat outdated and has been depreciated, it's only kept around now for historical preservation purposes. A far more comprehensive, accurate, and up-to-date FAQ is located on GrapheneOS' homepage, at https://grapheneos.org/faq

Using third-party apps to manage VPN settings is generally not a great idea; GrapheneOS contains its own system functionality to implement VPNs, which should be used instead of using apps to do so. https://grapheneos.org/faq#vpn-support Outside of that though, stuff that deals with VPNs isn't my strong suit since I haven't dealt with networking as much at this point, and I don't want to guess at what I don't know. 

We do have an IRC channel if you'd like to drop by to chat. I'm around sporadically, but we do have a large number of members there that may be able to comment, it's #grapheneos at irc.freenode.net 

Maybe see you there!
