### ISSUE TITLE
BFU/AFU & Cellebrite

### ISSUE THREAD

**Issue by rhclayto** [Peter-Easton/GrapheneOS-Knowledge#3]
I've read at https://libredd.it/r/privacy/comments/me4xjw/how_to_protect_your_phone_against_companies_such/ the assertion that the way Cellebrite, Grayshift, etc. extract data is by exploiting phones that are in AFU mode. According to the Reddit post's author, 'The reason your phone needs to be in BFU mode is because the encryption keys are stored in memory for your data, when the phone is powered on, but has been unlocked at least once. Forensic companies logically exploit this to extract almost all your phone data from your phone, without even needing to know your passcode.'

Does this apply to GrapheneOS (& is it even accurate)?

I have read the FAQ at https://github.com/Peter-Easton/GrapheneOS-Knowledge/blob/master/GrapheneOS-Security-Q%26A.md#what-security-measures-does-grapheneos-have-against-those-cell-phone-unlockers-used-by-the-military-like-cellebrite-graykey-etc-what-about-nation-states-with-unlimited-resources . It would seem to suggest that passphrase or PIN would be required in any event (delayed by throttling if the HSM is undefeated, but also even in the case that the Titan-M is defeated), contradicting the Reddit author's idea that if the phone has been unlocked once, encryption keys are floating around in memory & data can somehow be extracted without having to obtain the passphrase or PIN. Note: the author references iOS but other commenters suggest it applies to Android as well.

**Comment by Peter-Easton** [comment]
Hello rhclayto,

This FAQ is somewhat outdated and has been depreciated, it's only kept around now for historical preservation purposes. A far more comprehensive, accurate, and up-to-date FAQ is located on GrapheneOS' homepage, at https://grapheneos.org/faq

> I've read at https://libredd.it/r/privacy/comments/me4xjw/how_to_protect_your_phone_against_companies_such/ the assertion that the way Cellebrite, Grayshift, etc. extract data is by exploiting phones that are in AFU mode. According to the Reddit post's author, 'The reason your phone needs to be in BFU mode is because the encryption keys are stored in memory for your data, when the phone is powered on, but has been unlocked at least once. Forensic companies logically exploit this to extract almost all your phone data from your phone, without even needing to know your passcode.'
> 
> Does this apply to GrapheneOS (& is it even accurate)?

It is completely inaccurate.

There is a very detailed overview of the GrapheneOS encryption system is here: https://grapheneos.org/faq#encryption

When you hit "end session" on a second user profile on GrapheneOS, GrapheneOS ejects all the keys from memory for that given profile. Even if a hypothetical exploit were to exist to compromise the phone's memory, dumping the memory out of the phone after a session has been ended will not compromise the keys to the given profile because once the profile has been logged out the keys no longer reside in memory. The End Session button is unique to GrapheneOS, as of right now it's not available upstream or on other Android distributions.

The "owner" profile of the phone unlocks certain system configuration files that apply globally across the phone. As a result, the "owner" must be logged in in order to boot the phone. However, you don't need to store anything in that profile, and can simply delegate your usage to secondary profiles.

Secondary profiles are not accessible to any other profile but their own. The owner profile can create and delete profiles, as well as grant or deny secondary profiles the ability to send and make calls and text messages via the insecure legacy publicly switched telephone network on behalf of the handset, but cannot change, modify, or see the data in other profiles.

**Comment by Peter-Easton** [comment]
If you like, you can join the IRC channel at #grapheneos and #grapheneos-offtopic on irc.freenode.net if you have more questions, I'd be happy to answer them when I'm at my desk. 

See you there!

**Comment by rhclayto** [comment]
Hi Peter,

Wow. I got really excited about GrapheneOS & the philosophy behind it, but I joined the IRC channel & now I'm worried that the whole project might be a sinking ship (pirate joke!). Your captain has some serious issues. Megalomania? Persecution complex? Maybe simple immaturity? 

Somebody needs to keep Daniel Micay in a room somewhere coding, which he seems to be very good at, & not being the public face of your project, at which he is abysmally incompetent. Such an utterly abrasive fellow I have not encountered in a long while. He's going to drive any & every privacy-concerned general user far away.

Ugh, so disappointing. Cheers to you though, if someone like you could be the interface between the developers & the public, rather than Captain Ahab, everything would be so much better. Or maybe a hard fork is in order.

PS: I had multiple users on the IRC channel write me & say the same thing after I logged off of the channel.

**Comment by Peter-Easton** [comment]
Hello rhclayto,

I saw your interaction did not go well. It's a coincidentally been a difficult and bad time for our lead developer, and looks like you just came in at a bit of a bad time. I can still try to answer some of your questions politics aside, but I would ask you not to bad mouth our lead developer or bash the project.

You'd asked in the IRC channel [link](https://freenode.logbot.info/grapheneos/20210409#c7559559)  if there's there was a procedure someone would use to bypass the lockscreen, and for me to explain it in a non-technical way.

To my knowledge, to bypass the lock screen, you would need an exploit and for that you'd likely need to buy an exploit from an exploit broker to find a lockscreen bypass exploit. To get a sense of value on this, Zerodium's exploit brokering program lists the reward for an Android PIN bypass at up to [$100,000](https://zerodium.com/program.html) US Dollars as of this day. If anyone would be able to answer your question, it'd be them, for a fee.

This of course, assumes that such an exploit for the particular model of the phone, running the particular release of the operating system exists and is known to Zerodium (or whichever exploit broker you shop at) at the time you go looking for an exploit. However, it's also a good way to gauge how much hypothetical, advanced and determined threats would need to go in order to use the threat vector you've gotten in mind.

Note as well, that if a lockscreen is bypassed, if the keys aren't living in memory because the user has either ended the session via the "End Session" button, the data is said to be "at rest."  When data is "at rest" this means that the operating system does not currently possess the keys to the data on the drive, and it is not being used. As a result, the operating system, or anyone that has access to the drive either through the operating system, or via some other surreptitious means **cannot** read the files, **cannot** edit the files, and **cannot** modify the files.

**Comment by Peter-Easton** [comment]
This of course, assumes that such an exploit for the particular model of the phone, running the particular release of the operating system exists and is known to Zerodium (or whichever exploit broker you shop at) at the time you go looking for an exploit. However, it's also a good way to gauge how much hypothetical, advanced and determined threats would need to go in order to use the threat vector you've gotten in mind.
