### ISSUE TITLE
making notes regarding Wire

### ISSUE THREAD

**Issue by b3K1ndRw1nd** [Peter-Easton/GrapheneOS-Knowledge#5]
are you open to me adding info to the silver list about how to get Wire to work on grapheneOS? 

or is this documentation geared more towards "What works and what doesn't" rather than "how to make something work"?

**Comment by Peter-Easton** [comment]
Hi! 

This is just documentation that's geared toward what works and what doesn't, rather than how to make something work. Notifications on Wire have been a bit spotty last update, but I don't use Wire anymore. If this is false or you have information on what it needs, let me know and I will move it back to Gold.

**Comment by Peter-Easton** [comment]
Nevermind, actually, it should be back on Gold now.

**Comment by b3K1ndRw1nd** [comment]
@Peter-Easton if you want to put in on Gold, that's fine but one bug that wire has for GrapheneOS is that it cannot automatically connect to the wire server on boot, which effectively means you will not receive notification unless you first manually open the app. Not sure if you consider that Silver or Gold tier.

**Comment by Peter-Easton** [comment]
Sure. Give me a minute, and I will add that fiat. If it works as it's expected to sounds like Gold Tier, so I'll just add that it is not direct-boot aware and must be started manually.

**Comment by Peter-Easton** [comment]
Done. I've added that it must be started manually.
